# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_updated_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_updated_at', models.DateTimeField(editable=False)),
                ('email', models.CharField(max_length=127, unique=True)),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(blank=True, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactapp.ContactBook')),
            ],
        ),
        migrations.AddIndex(
            model_name='contactbook',
            index=models.Index(fields=['name'], name='contactapp__name_ce4331_idx'),
        ),
        migrations.AddIndex(
            model_name='contacts',
            index=models.Index(fields=['first_name', 'last_name'], name='contactapp__first_n_7c2978_idx'),
        ),
        migrations.AddIndex(
            model_name='contacts',
            index=models.Index(fields=['email'], name='contactapp__email_2cfadb_idx'),
        ),
    ]
