# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contactapp__first_n_7c2978_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contactapp__email_2cfadb_idx',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['first_name', 'last_name'], name='contactapp__first_n_27062d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contactapp__email_ed4a66_idx'),
        ),
    ]
